######################################################################
# Automatically generated by qmake (3.0) Sat Apr 25 15:50:38 2015
######################################################################

TEMPLATE = app
TARGET = app
INCLUDEPATH += .

# Input
SOURCES += main.cpp \
    menus.cpp \
    content_area.cpp \
    toolbar.cpp
QT += widgets

HEADERS += \
    content_area.h \
    toolbar.h
