######################################################################
# Automatically generated by qmake (3.0) Sat Apr 4 19:30:59 2015
######################################################################

TEMPLATE = app
TARGET = app
INCLUDEPATH += .

# Input
SOURCES += main.cpp
